name: Release Alerting Artefacts
on:
  push:
    branches:
      - opendistro-*

jobs:
  build:
    strategy:
      matrix:
        java: [12]

    name: Build and Release Alerting Plugin
    runs-on: [ubuntu-16.04]

    steps:
      - name: Checkout Alerting
        uses: actions/checkout@v1
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      
      - name: Run build
        run: |
          #!/bin/bash
          ./gradlew build buildDeb buildRpm --console=plain -Dbuild.snapshot=false
          artifact=`ls alerting/build/distributions/*.zip`
          rpm_artifact=`ls alerting/build/distributions/*.rpm`
          deb_artifact=`ls alerting/build/distributions/*.deb`
          
          aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/elasticsearch-plugins/opendistro-alerting/
          aws s3 cp $rpm_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/rpms/opendistro-alerting/
          aws s3 cp $deb_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs/opendistro-alerting/
          aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/downloads/*"
