name: Build and Test Alerting
on:
  push:
    branches:
      - master
      - opendistro-*

jobs:
  build:
    strategy:
      matrix:
        java: [12]

    name: Build and Test Alerting Plugin
    runs-on: [ubuntu-16.04]

    steps:
      - name: Checkout Alerting
        uses: actions/checkout@v1
        
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      
      - name: Run build
        run: |
          ./gradlew build
      
      - name: Pull and Run Docker
        run: |
          plugin=`ls alerting/build/distributions/*.zip`
          version=`echo $plugin|awk -F- '{print $2}'| cut -d. -f 1-3`
          plugin_version=`echo $plugin|awk -F- '{print $2}'| cut -d. -f 1-4`
          echo $version
          cd ..
          
          if docker pull opendistroforelasticsearch/opendistroforelasticsearch:$version
          then
            echo "FROM opendistroforelasticsearch/opendistroforelasticsearch:$version" >> Dockerfile
            echo "RUN if [ -d /usr/share/elasticsearch/plugins/opendistro_security ]; then /usr/share/elasticsearch/bin/elasticsearch-plugin remove opendistro_security; fi" >> Dockerfile
            echo "RUN if [ -d /usr/share/elasticsearch/plugins/opendistro_alerting ]; then /usr/share/elasticsearch/bin/elasticsearch-plugin remove opendistro_alerting; fi" >> Dockerfile
            echo "ADD alerting/alerting/build/distributions/opendistro_alerting-$plugin_version.zip /tmp/" >> Dockerfile
            echo "RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch file:/tmp/opendistro_alerting-$plugin_version.zip" >> Dockerfile
            
            docker build -t odfe-alerting:test .
          fi
          
      - name: Run Docker Image
        run: |
          cd ..
          docker run -p 9200:9200 -d -p 9600:9600 -e "discovery.type=single-node" odfe-alerting:test
          sleep 15
          curl -XGET http://localhost:9200/_cat/plugins
          
      - name: Run Alerting Test
        run: |
          cd alerting
          ../gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200
